name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    container: ghcr.io/kirinnee/nix-ci/nix-ci:latest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Use Cachix
        run: cachix use kirinnee-sample-binary-cache

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell nix/shells.nix -A releaser --run scripts/ci/release.sh
